# Generated by Django 3.2 on 2022-06-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_peddiodetalle_pedido'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PeddioDetalle',
            new_name='PedidoDetalle',
        ),
        migrations.RenameField(
            model_name='pedidodetalle',
            old_name='prodducto',
            new_name='producto',
        ),
    ]
